### ISSUE TITLE
Question: Extend base class

### ISSUE THREAD

**Issue by marcobiedermann** [tj/d3-bar#4]
How about creating a base `Chart` class and extend `BarChart` and all other charts from it?
E.g.

```
class Chart {
  …

  render() { … }
  update() { … }
}

class BarChart extends Chart {
  …

  renderBars() { … }
}

class LineChart extends Chart {
  …

  renderLines() { … }
}
```

This will save some repetitive code for all of your d3 projects.

**Comment by tj** [comment]
I'm not too worried about a bit of repetition, I prefer that they're isolated personally. If anything I'd like to compose the different bits but I'm not a fan of inheritance in most cases

**Comment by tj** [comment]
closing for now! might compose a few things later on
